(()=>{
  'use strict';
  const S={groups:[],ungrouped:[],selected:'',edit:false,draft:new Map(),ctx:null};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>new Intl.NumberFormat('ko-KR').format(Number(n||0));
  const initials=v=>String(v||'A').trim().slice(0,2).toUpperCase();
  const pLabel=p=>({google:'Google',kakao:'Kakao',naver:'Naver',apple:'Apple',microsoft:'Microsoft',oidc:'Custom OIDC'})[p]||p;
  const all=()=>[...S.groups.flatMap(g=>(g.projects||[]).map(p=>({...p}))),...(S.ungrouped||[]).map(p=>({...p}))];
  const group=id=>S.groups.find(g=>String(g.id)===String(id))||null;
  const project=id=>all().find(p=>String(p.id)===String(id))||null;
  const target=p=>S.draft.has(String(p.id))?S.draft.get(String(p.id)):(p.account_group_id||null);
  const hue=v=>{let h=0;for(const c of String(v||''))h=(h*31+c.charCodeAt(0))%360;return h};
  async function modal(title,html,ok='확인',danger=false){
    const w=document.createElement('div');w.className='ag-modal-backdrop';
    w.innerHTML=`<section class="ag-modal"><header><h3>${esc(title)}</h3><button data-cancel aria-label="닫기">×</button></header><div class="ag-modal-body">${html}</div><footer><button class="ag-btn ghost" data-cancel>취소</button><button class="ag-btn ${danger?'danger':'primary'}" data-ok>${esc(ok)}</button></footer></section>`;document.body.appendChild(w);
    return new Promise(r=>{let done=false;const end=v=>{if(done)return;done=true;w.remove();r(v)};w.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>end(false));w.querySelector('[data-ok]').onclick=()=>end(true);w.onclick=e=>{if(e.target===w)end(false)}})
  }
  function formModal(title,html,ok='저장'){
    const w=document.createElement('div');w.className='ag-modal-backdrop';w.innerHTML=`<section class="ag-modal"><header><h3>${esc(title)}</h3><button data-cancel aria-label="닫기">×</button></header><div class="ag-modal-body">${html}</div><footer><button class="ag-btn ghost" data-cancel>취소</button><button class="ag-btn primary" data-ok>${esc(ok)}</button></footer></section>`;document.body.appendChild(w);return w;
  }
  const badges=g=>{const rows=(g.providers||[]).filter(x=>x.environment_name==='production'&&x.enabled);return rows.length?rows.map(x=>`<span class="ag-provider ag-${esc(x.provider)}">${esc(pLabel(x.provider))}</span>`).join(''):'<span class="ag-provider muted">활성 소셜 없음</span>'};
  function card(p){const grouped=!!target(p);return `<article class="ag-project-card" draggable="${S.edit?'true':'false'}" data-project="${esc(p.id)}" style="--p-hue:${hue(p.id)}"><button class="ag-grip" tabindex="-1">⋮⋮</button><div class="ag-p-avatar">${esc(initials(p.name))}</div><div class="ag-p-copy"><strong>${esc(p.name)}</strong><small>${esc(p.monitor_public_url||p.slug||'')}</small><div><span class="ag-status ${p.status==='active'?'on':''}">${p.status==='active'?'활성':'비활성'}</span><span>${fmt(p.user_count)}명</span></div></div><span class="${grouped?'ag-shared':'ag-solo'}">${grouped?'공통 계정':'개별 계정'}</span></article>`}
  function box(g,ps){const selected=String(g.id)===String(S.selected);return `<section class="ag-group-box ${selected?'selected':''}" data-group="${esc(g.id)}" style="--g-hue:${hue(g.id)}"><header class="ag-group-head"><button class="ag-grip">⋮⋮</button><div class="ag-g-avatar">${esc(initials(g.name))}</div><div class="ag-g-copy"><h2>${esc(g.name)} <span>공통 계정</span></h2><p>이 박스 안 프로젝트는 하나의 계정 풀과 그룹 소셜 키를 공유합니다.</p></div><b>${ps.length}개 프로젝트</b><button class="ag-more">•••</button></header><div class="ag-project-zone" data-drop="${esc(g.id)}">${ps.map(card).join('')}<div class="ag-drop-card"><strong>＋ 여기에 프로젝트를 놓으세요</strong><small>이 그룹에 합류합니다.</small></div></div></section>`}
  function ungrouped(ps){return `<section class="ag-group-box ungrouped"><header class="ag-group-head"><button class="ag-grip">⋮⋮</button><div class="ag-g-avatar neutral">⌁</div><div class="ag-g-copy"><h2>그룹 없음 (미배정 프로젝트)</h2><p>각자 별도 계정 풀과 프로젝트 자체 소셜 키를 사용합니다.</p></div><b>${ps.length}개 프로젝트</b></header><div class="ag-project-zone" data-drop="">${ps.map(card).join('')}<div class="ag-drop-card leave"><strong>↧ 여기로 끌면 그룹 이탈</strong><small>보존된 프로젝트 자체 소셜 키를 다시 사용합니다.</small></div></div></section>`}
  function drawer(g){if(!g)return `<aside class="ag-drawer"><div class="ag-empty-drawer"><strong>그룹을 선택하세요</strong><p>그룹 박스를 선택하면 여기서 설정할 수 있습니다.</p></div></aside>`;return `<aside class="ag-drawer"><button class="ag-drawer-close" data-clear>×</button><span class="ag-drawer-kicker">선택한 그룹</span><div class="ag-drawer-title"><div class="ag-g-avatar">${esc(initials(g.name))}</div><h2>${esc(g.name)}</h2></div><label class="ag-field"><span>그룹 이름</span><input id="ag-name" value="${esc(g.name)}" maxlength="80"></label><label class="ag-field"><span>설명</span><textarea id="ag-desc" maxlength="500">${esc(g.description||'')}</textarea></label><div class="ag-read-status"><span>상태</span><b><i></i>${g.status==='disabled'?'비활성':'활성'}</b><small>그룹은 명시적으로 삭제하기 전까지 유지됩니다.</small></div><section class="ag-drawer-section"><h3>계정 정책</h3><div class="ag-policy"><b>●</b><div><strong>공통 계정 사용</strong><small>같은 그룹 프로젝트끼리만 이메일·비밀번호·소셜 identity를 공유합니다.</small></div></div></section><section class="ag-drawer-section"><div class="ag-section-title"><h3>그룹 소셜 키</h3><button data-providers>관리</button></div><div class="ag-provider-list">${badges(g)}</div><p>그룹 생성 시 대표 프로젝트 설정을 복제합니다. 대표 프로젝트가 나가도 그룹 키는 그대로 남습니다.</p></section><button class="ag-drawer-save" data-save-info>✓ 그룹 정보 저장</button><button class="ag-delete" data-delete>그룹 삭제</button></aside>`}
  function shell(main,draw){return `<div class="ag-shell"><header class="ag-top"><div class="ag-brand"><div>A</div><strong>AUTHHUB</strong><span>Admin</span></div><label class="ag-search">⌕ <input placeholder="프로젝트, 그룹, 사용자 등을 검색하세요..."><kbd>⌘ K</kbd></label><div class="ag-top-actions"><button>도움말</button><button>♢</button><span>A</span></div></header><aside class="ag-sidebar"><button data-nav="/overview">⌂ 대시보드</button><button data-nav="/users">♙ 사용자</button><button data-nav="/projects">▣ 프로젝트</button><button class="active">♧ 그룹 관리</button><button data-nav="/projects">⌘ 소셜 연동</button><button data-nav="/projects">◇ 로그인 정책</button><button data-nav="/integration">✉ 이메일/알림</button><button data-nav="/integration">◇ 보안 설정</button><button data-nav="/audit">▥ 감사 로그</button><div class="ag-side-foot"><strong>AuthHub</strong><span>통합 인증 관리 시스템</span><small>${esc(S.ctx?.version||'')}</small></div></aside><main class="ag-main">${main}</main>${draw}</div>`}
  function render(){if(!S.ctx)return;const buckets=new Map(S.groups.map(g=>[String(g.id),[]])),un=[];for(const p of all()){const t=target(p);if(t&&buckets.has(String(t)))buckets.get(String(t)).push({...p,account_group_id:t});else un.push({...p,account_group_id:null})}if(S.selected&&!group(S.selected))S.selected='';const dirty=S.draft.size;const head=`<div class="ag-page-head"><div><h1>그룹 관리 <small>?</small></h1><p>프로젝트를 그룹으로 묶어 공통 계정을 사용할지, 개별로 운영할지 직접 편집합니다.</p></div><div class="ag-edit-actions"><button class="ag-edit ${S.edit?'on':''}" data-edit><b>✎</b><span>${S.edit?'편집 모드':'편집 시작'}<small>${S.edit?'드래그하여 프로젝트를 이동하세요.':'그룹 구성을 직접 편집합니다.'}</small></span></button><button class="ag-save" data-save ${dirty?'':'disabled'}>✓ 변경사항 저장${dirty?` <b>${dirty}</b>`:''}</button></div></div><nav class="ag-tabs"><button class="active">그룹 보기</button><button data-nav="/projects">프로젝트 보기</button><button data-nav="/users">멤버십 매핑</button><button data-nav="/audit">설정 이력</button><button class="ag-add" data-add>＋ 그룹 추가</button></nav>`;const body=S.groups.map(g=>box(g,buckets.get(String(g.id))||[])).join('')+ungrouped(un);S.ctx.app.innerHTML=shell(`<div class="ag-page">${head}<div class="ag-canvas ${S.edit?'editing':''}">${body}</div></div>`,drawer(group(S.selected)));bind()}
  async function refresh(){S.ctx.loading(true);try{const d=await S.ctx.request('/admin/account-groups');S.groups=d.items||[];S.ungrouped=d.ungrouped||[]}catch(e){S.ctx.toast(e.message,'error')}finally{S.ctx.loading(false)}render()}
  async function stage(pid,gid){if(!S.edit)return;const p=project(pid);if(!p)return;const old=target(p);if(String(old||'')===String(gid||''))return;if(gid){S.ctx.loading(true);let v;try{v=await S.ctx.request(`/admin/account-groups/${encodeURIComponent(gid)}/projects/${encodeURIComponent(pid)}/preview`)}catch(e){S.ctx.toast(e.message,'error');return}finally{S.ctx.loading(false)}if(v.emailConflicts||v.identityConflicts){await modal('그룹 합류 충돌',`<div class="ag-impact danger"><strong>현재 이 프로젝트를 안전하게 합칠 수 없습니다.</strong><p>동일 이메일 ${fmt(v.emailConflicts)}건, 동일 소셜 identity ${fmt(v.identityConflicts)}건이 서로 다른 사용자로 존재합니다.</p></div>`);return}const names=(v.groupProviders||[]).filter(x=>x.environment_name==='production'&&x.enabled).map(x=>pLabel(x.provider));const ok=await modal('그룹에 합류',`<div class="ag-impact"><strong>소셜 로그인 키가 그룹 기준으로 전환됩니다.</strong><p><b>${esc(p.name)}</b>의 기존 소셜 키는 삭제하지 않고 보존합니다. 저장 후부터 인증에는 <b>${esc(v.groupName||group(gid)?.name||'선택 그룹')}</b>의 그룹 소셜 키${names.length?' ('+esc(names.join(', '))+')':''}를 사용합니다.</p></div><div class="ag-impact-note">기존 세션은 안전을 위해 종료됩니다. 그룹에서 이탈하면 프로젝트의 원래 소셜 키가 다시 활성화됩니다.</div>`,'그룹 합류');if(!ok)return;S.draft.set(String(pid),gid)}else{const g=group(old);const ok=await modal('그룹에서 이탈',`<div class="ag-impact"><strong>${esc(p.name)}을(를) 개별 계정으로 전환합니다.</strong><p>그룹 공통 계정/소셜 키 사용을 중단하고 프로젝트에 보존된 자체 소셜 키를 다시 사용합니다.</p></div><div class="ag-impact-note"><b>${esc(g?.name||'현재 그룹')}</b>과 그룹이 보관 중인 소셜 키는 삭제되지 않습니다. 그룹이 비어도 그대로 남습니다.</div>`,'그룹 이탈');if(!ok)return;S.draft.set(String(pid),null)}render()}
  async function saveDraft(){if(!S.draft.size)return;S.ctx.loading(true);try{for(const [pid,gid] of S.draft){const p=project(pid),old=p?.account_group_id||null;if(String(old||'')===String(gid||''))continue;if(gid)await S.ctx.request(`/admin/account-groups/${encodeURIComponent(gid)}/projects/${encodeURIComponent(pid)}`,{method:'POST',body:'{}'});else if(old)await S.ctx.request(`/admin/account-groups/${encodeURIComponent(old)}/projects/${encodeURIComponent(pid)}`,{method:'DELETE'})}S.draft.clear();S.edit=false;S.ctx.toast('그룹 변경사항을 저장했습니다. 계정 범위와 소셜 키 사용 기준이 새 구성으로 전환됐습니다.');await refresh()}catch(e){S.ctx.toast(e.message,'error')}finally{S.ctx.loading(false)}}
  async function addGroup(){const avail=all().filter(p=>!target(p));if(!avail.length){S.ctx.toast('대표 프로젝트로 사용할 미배정 프로젝트가 없습니다.','error');return}const w=formModal('새 계정 그룹',`<label class="ag-form-field"><span>그룹 이름</span><input id="ag-new-name" placeholder="예: Commerce 서비스 그룹"></label><label class="ag-form-field"><span>대표 프로젝트</span><select id="ag-rep">${avail.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select><small>대표 프로젝트의 Production/Staging 소셜 설정을 그룹 키로 복제합니다.</small></label><label class="ag-form-field"><span>설명</span><textarea id="ag-new-desc"></textarea></label><div class="ag-impact"><strong>대표 프로젝트의 소셜 키는 복사됩니다.</strong><p>프로젝트 원본 키는 그대로 보존됩니다. 대표 프로젝트가 나가도 그룹 복제본은 유지됩니다.</p></div>`,'그룹 생성');w.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>w.remove());w.querySelector('[data-ok]').onclick=async()=>{const name=w.querySelector('#ag-new-name').value.trim(),rep=w.querySelector('#ag-rep').value;if(!name)return;S.ctx.loading(true);try{const r=await S.ctx.request('/admin/account-groups',{method:'POST',body:JSON.stringify({name,description:w.querySelector('#ag-new-desc').value,representativeProjectId:rep})});w.remove();S.selected=r.id;S.ctx.toast('그룹을 만들고 대표 프로젝트의 소셜 키를 그룹에 복제했습니다.');await refresh()}catch(e){S.ctx.toast(e.message,'error')}finally{S.ctx.loading(false)}}}
  function providers(g){let env='production';const draw=()=>{const rows=(g.providers||[]).filter(x=>x.environment_name===env);const w=formModal('그룹 소셜 키',`<div class="ag-provider-tabs"><button class="${env==='production'?'active':''}" data-env="production">Production</button><button class="${env==='staging'?'active':''}" data-env="staging">Staging</button></div><div class="ag-provider-editor">${rows.map(p=>`<button data-provider="${esc(p.provider)}"><span>${esc(pLabel(p.provider))}</span><small>${p.enabled?'활성':'비활성'} · ${p.configured?'설정됨':'미설정'}</small><i>›</i></button>`).join('')}</div><div class="ag-impact-note">여기서 바꾼 키는 그룹의 모든 프로젝트에 적용됩니다. 프로젝트 자체 키는 계속 보존됩니다.</div>`,'닫기');w.querySelector('[data-ok]').onclick=()=>w.remove();w.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>w.remove());w.querySelectorAll('[data-env]').forEach(b=>b.onclick=()=>{env=b.dataset.env;w.remove();draw()});w.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>editProvider(g,env,b.dataset.provider,w));};draw()}
  function editProvider(g,env,pn,parent){const p=(g.providers||[]).find(x=>x.environment_name===env&&x.provider===pn)||{};const w=formModal(`${pLabel(pn)} · 그룹 키`,`<label class="ag-switch-row"><span><strong>로그인 수단 활성화</strong><small>그룹 전체 적용</small></span><input id="ag-enabled" type="checkbox" ${p.enabled?'checked':''}></label><label class="ag-form-field"><span>Client ID</span><input id="ag-client" placeholder="변경할 때만 입력"></label><label class="ag-form-field"><span>Client Secret</span><input id="ag-secret" type="password" placeholder="변경할 때만 입력" autocomplete="new-password"></label><label class="ag-form-field"><span>Scopes</span><input id="ag-scopes" placeholder="변경할 때만 입력"></label><div class="ag-impact-note">저장된 키 원문은 관리자 화면에 다시 노출하지 않습니다.</div>`);w.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>w.remove());w.querySelector('[data-ok]').onclick=async()=>{const payload={enabled:w.querySelector('#ag-enabled').checked},ci=w.querySelector('#ag-client').value.trim(),se=w.querySelector('#ag-secret').value,sc=w.querySelector('#ag-scopes').value.trim();if(ci)payload.clientId=ci;if(se)payload.clientSecret=se;if(sc)payload.scopes=sc;S.ctx.loading(true);try{await S.ctx.request(`/admin/account-groups/${encodeURIComponent(g.id)}/providers/${encodeURIComponent(env)}/${encodeURIComponent(pn)}`,{method:'PUT',body:JSON.stringify(payload)});w.remove();parent?.remove();S.ctx.toast('그룹 소셜 키를 저장했습니다.');await refresh()}catch(e){S.ctx.toast(e.message,'error')}finally{S.ctx.loading(false)}}}
  function bind(){const app=S.ctx.app;app.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>S.ctx.navigate(b.dataset.nav));app.querySelectorAll('[data-group]').forEach(x=>x.onclick=e=>{if(e.target.closest('[data-project],[data-drop]'))return;S.selected=x.dataset.group;render()});app.querySelector('[data-edit]')?.addEventListener('click',()=>{if(S.edit&&S.draft.size&&!confirm('저장하지 않은 이동을 취소할까요?'))return;if(S.edit)S.draft.clear();S.edit=!S.edit;render()});app.querySelector('[data-save]')?.addEventListener('click',saveDraft);app.querySelector('[data-add]')?.addEventListener('click',addGroup);app.querySelector('[data-clear]')?.addEventListener('click',()=>{S.selected='';render()});app.querySelector('[data-save-info]')?.addEventListener('click',async()=>{const g=group(S.selected);if(!g)return;S.ctx.loading(true);try{await S.ctx.request(`/admin/account-groups/${encodeURIComponent(g.id)}`,{method:'PATCH',body:JSON.stringify({name:app.querySelector('#ag-name').value,description:app.querySelector('#ag-desc').value})});S.ctx.toast('그룹 정보를 저장했습니다.');await refresh()}catch(e){S.ctx.toast(e.message,'error')}finally{S.ctx.loading(false)}});app.querySelector('[data-providers]')?.addEventListener('click',()=>{const g=group(S.selected);if(g)providers(g)});app.querySelector('[data-delete]')?.addEventListener('click',async()=>{const g=group(S.selected);if(!g)return;const ok=await modal('그룹 완전 삭제',`<div class="ag-impact danger"><strong>${esc(g.name)} 그룹을 완전히 삭제합니다.</strong><p>그룹 소셜 키는 삭제되고 소속 프로젝트는 개별 계정으로 분리됩니다. 각 프로젝트에 보존된 자체 소셜 키가 다시 활성화됩니다.</p></div>`,'그룹 삭제',true);if(!ok)return;S.ctx.loading(true);try{await S.ctx.request(`/admin/account-groups/${encodeURIComponent(g.id)}`,{method:'DELETE'});S.selected='';S.draft.clear();S.ctx.toast('그룹을 완전히 삭제했습니다.');await refresh()}catch(e){S.ctx.toast(e.message,'error')}finally{S.ctx.loading(false)}});app.querySelectorAll('[data-project]').forEach(c=>{c.onclick=e=>e.stopPropagation();c.ondragstart=e=>{if(!S.edit){e.preventDefault();return}e.dataTransfer.setData('text/plain',c.dataset.project);e.dataTransfer.effectAllowed='move';c.classList.add('dragging')};c.ondragend=()=>c.classList.remove('dragging')});app.querySelectorAll('[data-drop]').forEach(z=>{z.ondragover=e=>{if(!S.edit)return;e.preventDefault();z.classList.add('drag-over')};z.ondragleave=()=>z.classList.remove('drag-over');z.ondrop=e=>{if(!S.edit)return;e.preventDefault();z.classList.remove('drag-over');stage(e.dataTransfer.getData('text/plain'),z.dataset.drop||null)}})}
  window.AuthHubAccountGroups={render:async ctx=>{S.ctx=ctx;S.draft.clear();S.edit=false;await refresh()}};
})();
