(() => {
  'use strict';
  const cfg=window.AUTHHUB_CONFIG||{};
  const api=String(cfg.apiBase||'https://api-authhub.suaveforge.com').replace(/\/$/,'');
  let seq=0;
  const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const routeProjectId=()=>{const m=(location.hash.slice(1)||'').match(/^\/project\/([^/?#]+)/);return m?decodeURIComponent(m[1]):''};
  const toast=(message,type='ok')=>{const root=document.getElementById('toast-root');if(!root){alert(message);return}const el=document.createElement('div');el.className=`toast ${type==='error'?'error':''}`;el.innerHTML=`<i class="bi ${type==='error'?'bi-exclamation-circle':'bi-check-circle'}"></i><span>${esc(message)}</span>`;root.appendChild(el);setTimeout(()=>el.remove(),3400)};
  async function req(path,options={}){const res=await fetch(`${api}${path}`,{credentials:'include',...options,headers:{'content-type':'application/json',...(options.headers||{})}});const text=await res.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text||'request_failed'}}if(!res.ok)throw new Error(data.error||`요청 실패 (${res.status})`);return data}
  const defaults={mode:'light',layoutPreset:'default',brandName:'',logoUrl:'',accent:'#006340',backgroundColor:'#f5f6f7',backgroundImageUrl:'',textColor:'#111216',mutedTextColor:'#73767c',cardColor:'#ffffff',borderColor:'#dedede',fontFamily:'inter',buttonStyle:'soft',loginHeadline:'',signupHeadline:'',subtitle:''};
  const normalized=t=>({...defaults,...(t&&typeof t==='object'?t:{})});
  const hasTheme=t=>!!(t&&typeof t==='object'&&Object.keys(t).length);
  const field=(label,id,value,extra='')=>`<label class="at-field"><span>${esc(label)}</span><input id="${id}" class="at-input" value="${esc(value||'')}" ${extra}></label>`;
  const select=(label,id,value,options)=>`<label class="at-field"><span>${esc(label)}</span><select id="${id}" class="at-input">${options.map(([v,l])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
  function previewHtml(project,theme){
    const t=normalized(theme);const title=t.loginHeadline||'로그인';const subtitle=t.subtitle||'하나의 AuthHub 화면에서 안전하게 로그인합니다.';const brand=t.brandName||project.name||project.slug||'Service';
    return `<div class="at-preview-shell" style="--p-bg:${esc(t.backgroundColor)};--p-card:${esc(t.cardColor)};--p-text:${esc(t.textColor)};--p-muted:${esc(t.mutedTextColor)};--p-border:${esc(t.borderColor)};--p-accent:${esc(t.accent)}"><div class="at-preview-card at-btn-${esc(t.buttonStyle)}"><div class="at-preview-top"><div>${t.logoUrl?`<img src="${esc(t.logoUrl)}" alt="">`:''}<b>AUTHHUB</b><small>${esc(brand)}</small></div><span>닫기</span></div><h3>${esc(title)}</h3><p>${esc(subtitle)}</p><div class="at-preview-tabs"><b>로그인</b><span>회원가입</span></div><button type="button">Google로 계속하기</button><i>또는 이메일로</i><input aria-label="preview email" placeholder="이메일"><button class="primary" type="button">로그인</button></div></div>`;
  }
  function collect(panel){
    const val=id=>String(panel.querySelector(`#${id}`)?.value||'').trim();
    return {mode:val('at-mode'),layoutPreset:val('at-layout'),brandName:val('at-brand'),logoUrl:val('at-logo'),accent:val('at-accent'),backgroundColor:val('at-bg'),backgroundImageUrl:val('at-bg-image'),textColor:val('at-text'),mutedTextColor:val('at-muted'),cardColor:val('at-card'),borderColor:val('at-border'),fontFamily:val('at-font'),buttonStyle:val('at-button'),loginHeadline:val('at-login-headline'),signupHeadline:val('at-signup-headline'),subtitle:val('at-subtitle')};
  }
  function openEditor(project,onSaved){
    const current=normalized(project.login_theme);const backdrop=document.createElement('div');backdrop.className='at-backdrop';
    backdrop.innerHTML=`<section class="at-drawer" role="dialog" aria-modal="true" aria-labelledby="at-title"><header class="at-drawer-head"><div><div class="at-eyebrow">PROJECT LOGIN SKIN</div><h2 id="at-title">${esc(project.name||'프로젝트')} 로그인 스킨</h2><p>인증 엔진은 그대로 두고 허용된 디자인 토큰만 바꿉니다.</p></div><button class="at-close" type="button" aria-label="닫기"><i class="bi bi-x-lg"></i></button></header><div class="at-drawer-body"><div class="at-preview-wrap"><div class="at-preview-label">LIVE PREVIEW · LOGIN</div><div data-at-preview>${previewHtml(project,current)}</div></div><div class="at-editor-grid">${select('모드','at-mode',current.mode,[['light','Light'],['dark','Dark']])}${select('레이아웃','at-layout',current.layoutPreset,[['default','Default'],['media','Media'],['corporate','Corporate'],['minimal','Minimal']])}${field('서비스명','at-brand',current.brandName,'maxlength="80"')}${select('버튼 스타일','at-button',current.buttonStyle,[['square','Square'],['soft','Soft'],['pill','Pill']])}${field('로고 URL','at-logo',current.logoUrl,'type="url" placeholder="https://..."')}${select('폰트','at-font',current.fontFamily,[['inter','Inter'],['system','System'],['noto-sans-kr','Noto Sans KR']])}<div class="at-color-grid">${field('Accent','at-accent',current.accent,'type="color"')}${field('Background','at-bg',current.backgroundColor,'type="color"')}${field('Text','at-text',current.textColor,'type="color"')}${field('Muted text','at-muted',current.mutedTextColor,'type="color"')}${field('Card','at-card',current.cardColor,'type="color"')}${field('Border','at-border',current.borderColor,'type="color"')}</div>${field('배경 이미지 URL','at-bg-image',current.backgroundImageUrl,'type="url" placeholder="https://..."')}${field('로그인 상단 문구','at-login-headline',current.loginHeadline,'maxlength="120"')}${field('회원가입 상단 문구','at-signup-headline',current.signupHeadline,'maxlength="120"')}<label class="at-field at-wide"><span>보조 문구</span><textarea id="at-subtitle" class="at-input" maxlength="180">${esc(current.subtitle||'')}</textarea></label></div><div class="at-security-note"><i class="bi bi-shield-check"></i><span>임의 HTML/CSS/JS는 저장되지 않습니다. 잘못된 테마는 Hosted Login에서 기본 UI로 자동 fallback합니다.</span></div></div><footer class="at-drawer-foot"><button class="btn at-reset" type="button">기본 AuthHub 스킨 사용</button><div><button class="btn at-cancel" type="button">취소</button><button class="btn primary at-save" type="button"><i class="bi bi-check2"></i>스킨 저장</button></div></footer></section>`;
    document.body.appendChild(backdrop);const panel=backdrop.querySelector('.at-drawer');
    const close=()=>backdrop.remove();backdrop.addEventListener('mousedown',e=>{if(e.target===backdrop)close()});panel.querySelector('.at-close').onclick=close;panel.querySelector('.at-cancel').onclick=close;
    const redraw=()=>{panel.querySelector('[data-at-preview]').innerHTML=previewHtml(project,collect(panel))};panel.querySelectorAll('.at-input').forEach(el=>el.addEventListener('input',redraw));
    panel.querySelector('.at-reset').onclick=async()=>{if(!confirm('이 프로젝트의 커스텀 로그인 스킨을 제거하고 AuthHub 기본 디자인으로 되돌릴까요?'))return;try{await req(`/admin/projects/${encodeURIComponent(project.id)}/theme`,{method:'PUT',body:'{}'});toast('기본 AuthHub 스킨으로 되돌렸습니다.');close();onSaved()}catch(e){toast(e.message,'error')}};
    panel.querySelector('.at-save').onclick=async()=>{const button=panel.querySelector('.at-save');button.disabled=true;try{await req(`/admin/projects/${encodeURIComponent(project.id)}/theme`,{method:'PUT',body:JSON.stringify(collect(panel))});toast('로그인 스킨을 저장했습니다.');close();onSaved()}catch(e){const msg={invalid_theme_color:'색상 값을 확인하세요.',invalid_theme_url:'이미지는 HTTPS URL만 사용할 수 있습니다.'}[e.message]||e.message;toast(msg,'error')}finally{button.disabled=false}};
  }
  async function mount(){
    const projectId=routeProjectId();if(!projectId)return;const content=document.querySelector('#app .content');if(!content||content.querySelector('[data-admin-theme]'))return;const my=++seq;let project;try{project=await req(`/admin/projects/${encodeURIComponent(projectId)}`)}catch{return}if(my!==seq||projectId!==routeProjectId())return;
    const theme=project.login_theme||{};const custom=hasTheme(theme);const t=normalized(theme);const section=document.createElement('section');section.className='section at-section';section.dataset.adminTheme='1';
    const live=`https://authhub.suaveforge.com/login/?project=${encodeURIComponent(project.slug||project.monitor_project_id||'')}&redirect_uri=${encodeURIComponent(project.monitor_public_url||'https://authhub.suaveforge.com/')}`;
    section.innerHTML=`<div class="section-title"><div><h2>Login skin</h2><p>프로젝트별 Hosted Login 브랜딩입니다. 인증 로직·OAuth·세션에는 영향을 주지 않습니다.</p></div><div class="section-actions"><a class="btn" href="${esc(live)}" target="_blank" rel="noopener"><i class="bi bi-box-arrow-up-right"></i>실제 로그인 보기</a><button class="btn" data-at-edit type="button"><i class="bi bi-palette"></i>스킨 편집</button></div></div><div class="settings-card"><div class="setting-row"><div class="setting-label"><strong>현재 스킨</strong><small>테마가 없으면 AuthHub 기본 UI를 사용합니다.</small></div><div class="setting-value inline"><span class="badge ${custom?'green':'gray'}">${custom?'Custom':'Fallback'}</span><span>${esc(custom?(t.brandName||project.name):'AuthHub default')}</span></div></div><div class="setting-row"><div class="setting-label"><strong>표현 방식</strong><small>모드 · 레이아웃 · 버튼 · 폰트</small></div><div class="setting-value inline"><code>${esc(custom?t.mode:'light')}</code><code>${esc(custom?t.layoutPreset:'default')}</code><code>${esc(custom?t.buttonStyle:'soft')}</code><code>${esc(custom?t.fontFamily:'inter')}</code></div></div><div class="setting-row"><div class="setting-label"><strong>핵심 색상</strong><small>Hosted Login이 허용된 토큰만 렌더링합니다.</small></div><div class="setting-value inline at-swatches"><span style="--sw:${esc(t.accent)}" title="Accent"></span><span style="--sw:${esc(t.backgroundColor)}" title="Background"></span><span style="--sw:${esc(t.cardColor)}" title="Card"></span><span style="--sw:${esc(t.textColor)}" title="Text"></span></div></div></div>`;
    content.appendChild(section);section.querySelector('[data-at-edit]').onclick=()=>openEditor(project,()=>{section.remove();mount()});
  }
  let timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(mount,60)};new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});addEventListener('hashchange',()=>{seq++;schedule()});addEventListener('load',schedule);schedule();
})();
